//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_ORM_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public decimal Empno { get; set; }
        public string Ename { get; set; }
        public string City { get; set; }
        public decimal Sal { get; set; }
        public Nullable<int> Deptno { get; set; }
    
        public virtual Dept Dept { get; set; }
    }
}
